name: A workflow for my Hello World file
on: pull_request
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - uses: ./action-reaction
        with:
          REACTION_NUMBER: 0